### ISSUE TITLE
Set up Github permissions and CI automation

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#1]
@galargh need you help/sanity check :pray: 

This repo will be GOLANG code that produces a single binary and a Docker image for running it (similar to Kubo, but leaner).

https://github.com/protocol/github-mgmt does not exist, for now I've added permissions to this repo manually.

What is the proper way of doing below tasks?
- TBD  permissions match https://github.com/protocol/bifrost-infra + some additional IPFS stewards
- TBD things like github labels and CI config is kept in sync 

If any of the above is too difficult, we can move it to `ipfs/bifrost-gateway` for now, but would like to keep it in `protocol/` because its code specific to bifrost-infra.

**Comment by galargh** [comment]
>  ensure permissions match https://github.com/protocol/bifrost-infra + some additional IPFS stewards

AFAIK, the state of the art here is performing the actions manually (requires admin permission).

>  ensure things like github labels and CI config is kept in sync

I'm not aware of any workflows like that in this org. We could set it up though and maybe use web3-bot creds for lack of a better option.  

Both would be easier with GitHub Management but it's not a requirement.

**Comment by lidel** [comment]
Ok, discussed this during Rhea call today:
- We will be avoiding unnecessary work and security modeling by moving this repo to `ipfs` org
  - IPFS Stewards will be leading maintenance of this project for the foreseeable future
  - GitHub permissions management is done via https://github.com/ipfs/github-mgmt, makes it safer and more auditable
