### ISSUE TITLE
Signal back to the Graph Gateway that a request is done

### ISSUE THREAD

**Issue by aarshkshah1992** [ipfs/bifrost-gateway#127]
This will allow the Graph Gateway to record metrics around ttlb and total response size on a per end-user request basis. 
We need this to help investigate the RHEA/Kubo TTLB and response size discrepancies we are seeing.

**Comment by aschmahmann** [comment]
I don't really understand this issue. This is already done. Every function on that struct that asynchronously loads blocks after returning a lazy-loader to the caller (e.g. [GetBlock](https://github.com/ipfs/bifrost-gateway/blob/3e428607944983f7136ab00111c2e411d5b1426a/lib/graph_gateway.go#L535), [GetAll](https://github.com/ipfs/bifrost-gateway/blob/3e428607944983f7136ab00111c2e411d5b1426a/lib/graph_gateway.go#L553), [Head](https://github.com/ipfs/bifrost-gateway/blob/3e428607944983f7136ab00111c2e411d5b1426a/lib/graph_gateway.go#L576) , ...). The only annoying exception is [Get](https://github.com/ipfs/bifrost-gateway/blob/main/lib/graph_gateway.go#L520-L521) which also works it's just not as clean as the others.

If you have more things you want to put into the close functions you can file an issue/PR with what you want in there.

**Comment by aarshkshah1992** [comment]
@aschmahmann
