### ISSUE TITLE
error: Saturn data did not match given hash

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#16]
@hacdias mind looking into why stdout gets spamed with messages like ones below?

```
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmVv6aC9qcfEr7db155WUWvzE8dj9nD7oKAkwAJXGVnCij
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmR6hSR7jQygGCd9FjmTWF2nZgVsjQjEGqoPnWHHbvxp3W
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmbnP2sCk6AEqGWrM8DBtUNfQfoZBnEgKX5gceAxJFnj44
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmcUSpZNzHGUnrdFGr4Mowsq3izzrExic8j45Lo6q9Stgu
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmT7Qe9MLouG1dfqkBx1CG391L58hLsHRMbrw6qCLXYjR7
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmT7Qe9MLouG1dfqkBx1CG391L58hLsHRMbrw6qCLXYjR7
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmcUSpZNzHGUnrdFGr4Mowsq3izzrExic8j45Lo6q9Stgu
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmcUSpZNzHGUnrdFGr4Mowsq3izzrExic8j45Lo6q9Stgu
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmbBiyK1Uf7naVeWH5CgacnNYmpHoKdNCkKhNF3JZxTvoK
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmbBiyK1Uf7naVeWH5CgacnNYmpHoKdNCkKhNF3JZxTvoK
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmT7Qe9MLouG1dfqkBx1CG391L58hLsHRMbrw6qCLXYjR7
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmbBiyK1Uf7naVeWH5CgacnNYmpHoKdNCkKhNF3JZxTvoK
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmT7Qe9MLouG1dfqkBx1CG391L58hLsHRMbrw6qCLXYjR7
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmbfKn7MJjetHCRVjj2qQL7vKsdQ8wKuHe3pZjT79YEdx6
got QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc vs QmbfKn7MJjetHCRVjj2qQL7vKsdQ8wKuHe3pZjT79YEdx6
...
```

Are these related to hash verification errors? If you browse ipfs website long enough, Saturn will fail and we get this:

> ![2023-02-08-044911_822x146_scrot](https://user-images.githubusercontent.com/157609/217427885-0e632fe6-64d7-471d-b5cc-fd3462eccd32.png)

## Suggested improvements

- dont spam stdout  :upside_down_face:  if we really need to, write summary once a minute (N of M blocks returned by saturn were invalid, print which PoPs were at fault)
- bifrost-gateway should not fail like this. It must be robust enough to retry block read using different PoP, and blacklist PoPs that return garbage for some time.

**Comment by hacdias** [comment]
@lidel this errors (and stdout prints) come from caboose https://github.com/filecoin-saturn/caboose/blob/main/pool.go#L266

CC @willscott

**Comment by willscott** [comment]
it's all a single bad hash - i wonder if it's a 503 or similar error from the underlying nodes?

**Comment by willscott** [comment]
or potentially a 404 where the cache miss behind saturn is failing?

that said, the saturn L1s would be not returning the expected http error code in that case

**Comment by hacdias** [comment]
@willscott it's a 503:

```
$ ipfs block get QmPciteMQZnB6swbx35qA9geqe4AmESFJAM3Pa9WoxdcNc
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by lidel** [comment]
Spam is gone. Closing.
Clear reason why caboose failed is in debug longs since https://github.com/ipfs/bifrost-gateway/pull/44
