### ISSUE TITLE
Publish Docker images

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#2]
_(When we have go code that produces a single binary)_

Produce docker images similar to https://hub.docker.com/r/ipfs/kubo/tags,
this makes it easier to deploy as part of https://github.com/protocol/bifrost-infra

This repo needs to publish Docker tags on
- every push to `main` branch  (`main-latest`, `main-2023-01-31-4e8271b`)
- every release  (`latest`, `v0.0.1`)

**Comment by lidel** [comment]
@galargh @gmasgras is there docker hub org we can use for this, or should we use https://hub.docker.com/r/ipfs/ for now (and move this repo there) ?

**Comment by galargh** [comment]
I don't know any more suitable docker hub accounts. Just throwing it out there that creating a new one is also an option.

**Comment by lidel** [comment]
@galargh  need your help with `DOCKER_PASSWORD` for `ipfsbot` account.
The `docker hub token used by go-ipfs GH actions` shared with me via the vault is no longer valid:

- https://github.com/ipfs/bifrost-gateway/actions/runs/4126150673/jobs/7127680712#step:6:3

**Comment by lidel** [comment]
Secrets set up, waiting for the first build to finish:
https://github.com/ipfs/bifrost-gateway/actions/runs/4126150673/jobs/7129662282

**Comment by lidel** [comment]
Done :partying_face: 

```console
$ docker pull ipfs/bifrost-gateway:main-latest
$ docker run --rm -it --net=host ipfs/bifrost-gateway:main-latest
...
bifrost-gateway version 2023-02-08-af343aa
2023/02/08 18:15:07 Path gateway listening on http://127.0.0.1:8081
2023/02/08 18:15:07   Smoke test (JPG): http://127.0.0.1:8081/ipfs/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi
2023/02/08 18:15:07 Subdomain gateway listening on dweb.link and http://localhost:8081
2023/02/08 18:15:07   Smoke test (Subdomain+DNSLink+UnixFS+HAMT): http://localhost:8081/ipns/en.wikipedia-on-ipfs.org/
2023/02/08 18:15:07 Legacy RPC at /api/v0 provided by https://node0.delegate.ipfs.io https://node1.delegate.ipfs.io https://node2.delegate.ipfs.io https://node3.delegate.ipfs.io
2023/02/08 18:15:07 Metrics exposed at http://127.0.0.1:8041/debug/metrics/prometheus
```
