### ISSUE TITLE
internalWebError: %!s(<nil>)

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#23]
Opening `bafybeiggvykl7skb2ndlmacg2k5modvudocffxjesexlod2pfvg5yhwrqm` errored badly:

![2023-02-09-031728_1707x406_scrot](https://user-images.githubusercontent.com/157609/217700099-e1d6922f-0dd5-40c1-b6a2-6822cc141c63.png)

we should track down what produces errors like this, and improve them

**Comment by hacdias** [comment]
@lidel check https://github.com/ipfs/go-libipfs/pull/160

**Comment by lidel** [comment]
Thanks, switched to it, closing (we will open a new one when error appears again with details)
