### ISSUE TITLE
Expose configuration for necessary HTTP endpoints

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#3]
This is a quick dump of things what need to be configurable.

My initial proposal is to use env variables, which removes the need for babysitting config file.

So far, things we need to be able to configure are URLs of HTTP endpoints.

## Saturn Orchestrator endpoint

```sh
SATURN_ORCHESTRATOR="https://orchestrator.strn.pl"
```

We don't want [it hardcoded like this](https://github.com/filecoin-saturn/caboose/blob/e177ccac5260eab23fb4235bcc743ff383d8da82/cmd/caboose/main.go#L41), switching to alternative endpoint should not require recompiling binary.  

## Kubo RPC /api/v0 endpoint(s)

I propose space separated pool, we use them in random order to spread the load: 

```sh
KUBO_RPC="https://node0.delegate.ipfs.io https://node0.delegate.ipfs.io https://node1.delegate.ipfs.io https://node2.delegate.ipfs.io https://node3.delegate.ipfs.io"
```

 RPC endpoints that will be used:
  - `/api/v0/resolve` for resolving   `/ipns/{id}` to `/ipfs/{cid}` (until we have delegated IPNS lookups over IPNI)
  - we will be redirecting / proxying  legacy `/api/v0` endpoints exposed on `ipfs.io` (to minimize blast radius)

**Comment by willscott** [comment]
with the orchestrator we also will need a log submission URL from the environment as well

**Comment by lidel** [comment]
Done: 

https://github.com/ipfs/bifrost-gateway/blob/42dd3fb3a2b298e03e7c7e07eb30aa7d992bd1b9/Dockerfile#L66-L71
