### ISSUE TITLE
Delegate resolution of  DNSlink and IPNS records

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#5]
Initial idea (for Feb 17 binary)
- For resolving `/ipns/id` content paths to `/ipfs/cid` ones
  - Delegate RPC at  `https://node[0-2].delegate.ipfs.io/api/v0/resolve` (it handles both DNSlink and IPNS)
  - (TBD) if we need  local cache per `id` to avoid sending lookup, we can do it in two stages: 
    - naive mvp can be 1 minute LRU cache, matching current behavior in Kubo 0.18 ([which we want to fix long term](https://github.com/ipfs/kubo/issues/1818#issuecomment-1015849462))
    - correct cache is based on record TTL, so we reuse resolution for subsequent requests
      - this may require us to switch away from `/api/v0/resolve` and handle IPNS and DNSLink separately
        - DNSLink: run own DNS lookup for TXT record, and cache based on TTL of TXT record
        - IPNS record: use `/api/v0/routing/get` and cache based on TTL of the IPNS record
- For resolving raw IPNS record
  - Delegate RPC at  `https://node[0-2].delegate.ipfs.io/api/v0/routing/get` (cc @hacdias  to confirm, I believe we already do this is tests)
- Ensure resolution is as fast as possible:
  - run[ IPNS over Pubsub](https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#ipns-pubsub) and [Accelerated dht client](https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#accelerated-dht-client)
  - have a caching DNS server set up or use reliable [catch-all DoH endpoint for `.`](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#dns)
  
Long term, we want to use delegated HTTP routing for IPNS (follow-up for [IPIP-337](https://github.com/ipfs/specs/pull/337), when that API supports IPNS lookups), and DoH for DNSLink (https://github.com/libp2p/go-doh-resolver/ ?)

**Comment by hacdias** [comment]
@lidel I wonder if using the `?type=ipns-record` couldn't also be an option so would not necessarily need to rely on the RPC API.

**Comment by lidel** [comment]
@hacdias we won't have `?type=ipns-record` because bifrost-gateway we will be the gateway that is supposed to implement it. We won't be running DHT client (no go-libp2p is hard requirement for bifrost-gateway binary atm), and we don't have https://github.com/ipfs-shipyard/someguy/issues/15 so the only option that works for Feb 17 deliverable is `/api/v0/routing/get` from preexisting delegates.

I filled https://github.com/protocol/bifrost-infra/issues/2327 to expose `/api/v0/routing/get` there.

**Comment by lidel** [comment]
Done in https://github.com/ipfs/bifrost-gateway/pull/19
