### ISSUE TITLE
Support DNSLink on ENS (move namesys defaults out of Kubo)

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#60]
## Problem

bifrost-gateway must have feature and behavior parity with Kubo, but we have a bug around ENS:

- https://bifrost-gateway.ipfs.io/ipns/blog.almonit.eth fails because DNSLink can't be resolved
- https://ipfs.io/ipns/blog.almonit.eth (Kubo) works

## Potential cause 

Seems that we are running different namesys config than Kubo.

It should use the same set of [`defaultResolvers`](https://github.com/ipfs/kubo/blob/d82dec32482bb4ece33d3e867c4f615eea6bb487/core/node/dns.go#L16) to support ENS and UD, as noted in [the config docs](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#dns),  but `*.eth` resolution does not work atm. 

## Cleanup proposal

Move [`defaultResolvers`](https://github.com/ipfs/kubo/blob/d82dec32482bb4ece33d3e867c4f615eea6bb487/core/node/dns.go#L16) to one of upstream libraries, and make them implicit default to avoid ENS failures like this one.

### Option A: move   to go-namesys (global)

- Move  [`defaultResolvers`](https://github.com/ipfs/kubo/blob/d82dec32482bb4ece33d3e867c4f615eea6bb487/core/node/dns.go#L16) from Kubo to https://github.com/ipfs/go-namesys
- Make namesys apply default resolvers by default

This applies defaults to both DNSLinks and Multiaddrs, allowing use of `*.eth` in [`/dnsaddr`](https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md) too

### Option B: move to go-libipfs/gateway (minimal, scoped to DNSLinks)

- Move  [`defaultResolvers`](https://github.com/ipfs/kubo/blob/d82dec32482bb4ece33d3e867c4f615eea6bb487/core/node/dns.go#L16) from Kubo to https://github.com/ipfs/go-libipfs/tree/main/gateway
- https://github.com/ipfs/go-libipfs/pull/176 introduces `WithNameSystem` option for passing custom namesys – we could use that in bifrost-gateway to pass namesys with these additional resolvers, OR
- (optional) we could make the implicit namesys used in go-libipfs/gateway, so everyone using the library gets the same behavior

This would only apply to DNSLinks, but that is enough given the utility of ENS today (just DNSLinks).

----

@hacdias @aschmahmann  Thoughts?

 I feel (B) may be cleaner:
- `WithNameSystem` allows users to pass custom resolvers 
- if no `WithNameSystem` is passed we apply [`defaultResolvers`](https://github.com/ipfs/kubo/blob/d82dec32482bb4ece33d3e867c4f615eea6bb487/core/node/dns.go#L16) on the library level as implicit default

**Comment by hacdias** [comment]
@lidel I think the idea of moving to `go-libipfs/gateway` (approach B) is the best option to go, as it allows re-use without cluttering too much our other general packages (`go-namesys`).

**Comment by lidel** [comment]
@hacdias sgtm. do you prefer to do it as part of https://github.com/ipfs/kubo/pull/9681,or after?

**Comment by hacdias** [comment]
I think after would be better.

**Comment by hacdias** [comment]
@lidel I decided doing it _during_.
