### ISSUE TITLE
Fix CAR and other metrics 

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#76]
Some things I've noticed while adding CAR panels to  [bifrost-gw staging](https://protocollabs.grafana.net/d/d6FxxgJ4k/bifrost-gw-staging-metrics?orgId=1&from=now-12h&to=now&refresh=1m#) (see "bifrost-gateway daemon" section)

- [x] car metrics (histograms) looks to be capped at 1m – need to verify in https://github.com/filecoin-saturn/caboose/issues/76
  - [x] `*_car_peer_success|failure*` (caboose)
  - [x] `*_car_success|failure*` (caboose)
- [x] car size metric (`*_fetch_size`) looks to be capped at 4MiB –  need to verify https://github.com/filecoin-saturn/caboose/issues/75
- [x] boxo/gateway  – https://github.com/ipfs/boxo/pull/265
  - [x] IPFSBackend  aapi call capped at 1m 
  - [x] GET durations (global and per type) capped at 1m

I think the first step is to add more buckets beyond 1m, let's say  until 5m.

**Comment by willscott** [comment]
* I don't see limits for 4MiB / 1min in caboose code anywhere obvious - i wonder if these are limits imposed from the saturn side?

**Comment by aarshkshah1992** [comment]
@willscott Identified RC for #75 . https://github.com/filecoin-saturn/caboose/pull/77

4Mib was because of using block size buckets  for CAR size histrogram. The above PR takes care of that.

**Comment by lidel** [comment]
Closed in https://github.com/ipfs/bifrost-gateway/commit/185727bb1427e6983809b7c2acf71753f5fe869a (https://github.com/filecoin-saturn/caboose/pull/77) and  https://github.com/ipfs/bifrost-gateway/commit/d8d28495c31798b25510812af9fcb0028ff1f197 (https://github.com/ipfs/boxo/pull/265)
