### ISSUE TITLE
Expose the same logging capability as Kubo

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#9]
I believe our infra is logging request details and then processing it, we need to keep ability to have that after switching to bifrost-gateway binary.

Kubo can be run with adjusted log level, we could do the same here, 
but i dont know if the HTTP access logs come from Kubo, or Nginx in front of it.

**Comment by lidel** [comment]
@gmasgras mind sharing some info about how you are gathering logs currently?

**Comment by willscott** [comment]
presumably we'll use `go-log` internally?
i think your question is if we need a specific mode, like json output, and if so how that's configured?

**Comment by gmasgras** [comment]
We log `ERROR` level Kubo output (`IPFS_LOGGING=ERROR`) but don't alert on it.  Also used `IPFS_LOGGING_FMT=json` at some point IIRC

**Comment by hacdias** [comment]
@lidel any difference between this and #26?

**Comment by lidel** [comment]
No, closed in https://github.com/ipfs/bifrost-gateway/pull/30 (includes docs)
