### ISSUE TITLE
Investigate why success rate gets worse over time

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#92]
Restarting `biforst-gateway` on staging produces very close success rate, but over time, it erodes into worse and worse state:

Inspect yourself:
- [overview@stg board](https://protocollabs.grafana.net/d/oMul13fVz/gateway-metrics-overview?orgId=1&var-env=stage1&var-percentile=All&var-instance=All&var-instance_old=All&var-instance_rhea=All&var-loadbalancer=All&var-loadbalancer_old=All&var-loadbalancer_rhea=All&var-bank=All&var-location=All&var-interval=15m&from=1681142410496&to=1681228810496)
- detailed [bifrost-gw staging](https://protocollabs.grafana.net/d/d6FxxgJ4k/bifrost-gw-staging-metrics?orgId=1&from=1681142303463&to=1681228703463)

Summary from the latter:

>  ![Screenshot 2023-04-11 at 16-49-25 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/231202795-75a1187d-2e37-41c7-8de0-c112487afb35.png)

Some ideas/thoughts why:

- in-memory block cache  perf regression is unlikely, cache size is symbolic, aims to limit roundtrips per requests. 
  Staging  runs with  BLOCK_CACHE_SIZE=16k (https://github.com/ipfs/bifrost-gateway/issues/47#issuecomment-1496480533) and the slowness will happens way after that is filled up multiple times, and we see on the next graph the duration increase of CAR fetch happens on Caboose side:
  > ![Screenshot 2023-04-11 at 17-40-26 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/231216454-95b46553-a4db-465d-84ea-1821ed1c60ec.png)
  > ![Screenshot 2023-04-11 at 17-43-42 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/231216852-b2fef5d7-efb1-4f05-82d2-6d3ff0272ec8.png)

  
- Saturn L1 pool health gets worse for some reason:
  > ![Screenshot 2023-04-11 at 16-56-42 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/231203315-94c3b080-0c7c-4746-8381-d50ef724ed7c.png)
- Saturn per-L1 CAR fetch durations increase while other durations stay the same:
  >  ![2023-04-11_17-37](https://user-images.githubusercontent.com/157609/231215198-0c2321dc-1696-4496-abae-cb44c43182c5.png)

- HTTP 499s suggests clients giving up before they get our response, which is aligned with things getting slower over time, and more and more clients giving up waiting for response. This is not specific to Rhea, the old mirrored node that runs Kubo is also seeing more 499s over time, but it is less prominent:
  >  ![Screenshot 2023-04-11 at 19-08-23 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/231238080-6cbc3acd-7112-4384-8a89-998ea7cf0508.png)

Any feedback / thoughts / hypothesis are welcome. :pray:

**Comment by lidel** [comment]
fyi the problem is still present -- after a reboot it performs well, then, after  ~1h things get visibly worse (499s are gone for 1h, and then back, very weird):

>  ![2023-04-18_15-22](https://user-images.githubusercontent.com/157609/232790872-6136a10a-bfbc-4350-a617-be718c12563a.png)

**Comment by lidel** [comment]
Ok, got bit more clarity. Works fine for a while, then erodes, and we see CPUs being capped when it happens:

>  ![Screenshot 2023-04-24 at 12-47-48 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/233980883-6ac92f0c-4430-490d-ba7c-7919cc3d0fbb.png)


Looks like  a bug either in `GRAPH_BACKEND=true` or the new Caboose -- non-staging boxes run older version with graph backend disabled and have no CPU issues:  

> ![Screenshot 2023-04-24 at 13-12-07 View panel - bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/233980521-75f8a911-6850-4a43-81bb-4f2f3ebc022e.png)

> ![2023-04-24_13-09](https://user-images.githubusercontent.com/157609/233979675-e1ba5b9e-26b2-41c9-be44-8f3ae51a992b.png)

**Comment by aarshkshah1992** [comment]
@lidel The new Caboose wasn't there when we reported this issue two weeks back. So I'd be more suspicious of something going wrong with `GRAPH_BACKEND=true`

**Comment by lidel** [comment]
`GRAPH_BACKEND=false` looks solid, so we have confirmation the problem is limited to `GRAPH_BACKEND=true`:

>  ![2023-04-24_20-08](https://user-images.githubusercontent.com/157609/234080212-140a8714-97b7-4cd0-9d0b-497045897639.png)

**Comment by BigLep** [comment]
Related PR: https://github.com/ipfs/bifrost-gateway/pull/102

**Comment by lidel** [comment]
![Uploading 2023-04-26_19-25.png…]()
