### ISSUE TITLE
Expose /debug/pprof

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#99]
To investigate issues like #92 we need to port some features from Kubo and expose them on the "metrics" port, potential candidates:

> - goroutine dump
>   - `curl localhost:5001/debug/pprof/goroutine\?debug=2 > ipfs.stacks`
> - 30 second cpu profile
>   - `curl localhost:5001/debug/pprof/profile > ipfs.cpuprof`
> - heap trace dump
>   - `curl localhost:5001/debug/pprof/heap > ipfs.heap`
> - memory statistics (in json, see "memstats" object)
>   - `curl localhost:5001/debug/vars > ipfs.vars`
> - system information
>   - `ipfs diag sys > ipfs.sysinfo`

Ref. https://github.com/ipfs/kubo/blob/master/docs/debug-guide.md

**Comment by lidel** [comment]
@willscott  @aarshkshah1992 
with this, we could debug staging over ssh (incl. caboose)

**Comment by willscott** [comment]
it looks like we already have this on the metrics port

**Comment by willscott** [comment]
https://github.com/ipfs/bifrost-gateway/blob/main/handlers.go#L34-L38

**Comment by lidel** [comment]
Indeed! Adin added them already :raised_hands:  

I'll reboot staging with `GRAPH_BACKEND=true` and we wait a few hours until it gets wonky again. 
Let's continue in #92
